# Generated by Django 5.2.6 on 2025-11-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Librarian',
        ),
    ]
